export const namesOfAllah = [
    { number: 1, arabic: 'الله', transliteration: 'Allah', meaning: 'The Greatest Name' },
    { number: 2, arabic: 'الرَّحْمَن', transliteration: 'Ar-Rahman', meaning: 'The All-Merciful' },
    { number: 3, arabic: 'الرَّحِيم', transliteration: 'Ar-Raheem', meaning: 'The Most Merciful' },
    { number: 4, arabic: 'الْمَلِك', transliteration: 'Al-Malik', meaning: 'The King' },
    { number: 5, arabic: 'الْقُدُّوس', transliteration: 'Al-Quddus', meaning: 'The Most Holy' },
    { number: 6, arabic: 'السَّلَام', transliteration: 'As-Salam', meaning: 'The Source of Peace' },
    { number: 7, arabic: 'الْمُؤْمِن', transliteration: 'Al-Mu\'min', meaning: 'The Granter of Security' },
    { number: 8, arabic: 'الْمُهَيْمِن', transliteration: 'Al-Muhaymin', meaning: 'The Guardian' },
    { number: 9, arabic: 'الْعَزِيز', transliteration: 'Al-Aziz', meaning: 'The All-Mighty' },
    { number: 10, arabic: 'الْجَبَّار', transliteration: 'Al-Jabbar', meaning: 'The Compeller' },
    { number: 11, arabic: 'الْمُتَكَبِّر', transliteration: 'Al-Mutakabbir', meaning: 'The Supreme' },
    { number: 12, arabic: 'الْخَالِق', transliteration: 'Al-Khaliq', meaning: 'The Creator' },
    { number: 13, arabic: 'الْبَارِئ', transliteration: 'Al-Bari', meaning: 'The Evolver' },
    { number: 14, arabic: 'الْمُصَوِّر', transliteration: 'Al-Musawwir', meaning: 'The Fashioner' },
    { number: 15, arabic: 'الْغَفَّار', transliteration: 'Al-Ghaffar', meaning: 'The Constant Forgiver' },
    { number: 16, arabic: 'الْقَهَّار', transliteration: 'Al-Qahhar', meaning: 'The All-Prevailing One' },
    { number: 17, arabic: 'الْوَهَّاب', transliteration: 'Al-Wahhab', meaning: 'The Supreme Bestower' },
    { number: 18, arabic: 'الرَّزَّاق', transliteration: 'Ar-Razzaq', meaning: 'The Provider' },
    { number: 19, arabic: 'الْفَتَّاح', transliteration: 'Al-Fattah', meaning: 'The Supreme Solver' },
    { number: 20, arabic: 'الْعَلِيم', transliteration: 'Al-Aleem', meaning: 'The All-Knowing' },
    // Adding more for a decent grid
    { number: 21, arabic: 'الْقَابِض', transliteration: 'Al-Qabid', meaning: 'The Withholder' },
    { number: 22, arabic: 'الْبَاسِط', transliteration: 'Al-Basit', meaning: 'The Extender' },
    { number: 23, arabic: 'الْخَافِض', transliteration: 'Al-Khafid', meaning: 'The Reducer' },
    { number: 24, arabic: 'الرَّافِع', transliteration: 'Ar-Rafi', meaning: 'The Exalter' },
    { number: 25, arabic: 'الْمُعِزّ', transliteration: 'Al-Mu\'izz', meaning: 'The Honourer' },
    { number: 26, arabic: 'الْمُذِلّ', transliteration: 'Al-Muzil', meaning: 'The Dishonourer' },
    { number: 27, arabic: 'السَّمِيع', transliteration: 'As-Sami', meaning: 'The All-Hearing' },
    { number: 28, arabic: 'الْبَصِير', transliteration: 'Al-Basir', meaning: 'The All-Seeing' },
    { number: 29, arabic: 'الْحَكَم', transliteration: 'Al-Hakam', meaning: 'The Impartial Judge' },
    { number: 30, arabic: 'الْعَدْل', transliteration: 'Al-Adl', meaning: 'The Utterly Just' }
];
